### ISSUE TITLE
RaftActor might delete committed entries

### ISSUE THREAD

**Issue by xirc** [lerna-stack/akka-entity-replication#152]
The following errors happened when some failure-injection tests (like one AZ down):

```
ERROR   akka.actor.OneForOneStrategy    xxx-akka.actor.internal-dispatcher-4  akka://xxx/system/sharding/raft-shard-xxx-replica-group-2/1/1 -       Term not found at lastApplied: 7317     java.lang.IllegalStateException: Term not found at lastApplied: 7317
    at lerna.akka.entityreplication.raft.RaftMemberData.resolveSnapshotTargets(RaftMemberData.scala:416)
    at lerna.akka.entityreplication.raft.RaftMemberData.resolveSnapshotTargets$(RaftMemberData.scala:405)
    at lerna.akka.entityreplication.raft.RaftMemberDataImpl.resolveSnapshotTargets(RaftMemberData.scala:539)
    at lerna.akka.entityreplication.raft.RaftActor.handleSnapshotTick(RaftActor.scala:496)
    at lerna.akka.entityreplication.raft.Follower$$anonfun$followerBehavior$1.applyOrElse(Follower.scala:35)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at lerna.akka.entityreplication.raft.RaftActor.akka$persistence$Eventsourced$$super$aroundReceive(RaftActor.scala:124)
    at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:923)
    at akka.persistence.Eventsourced.aroundReceive$$original(Eventsourced.scala:251)
    at akka.persistence.Eventsourced.aroundReceive(Eventsourced.scala:148)
    at akka.persistence.Eventsourced.aroundReceive$(Eventsourced.scala:250)
    at lerna.akka.entityreplication.raft.RaftActor.aroundReceive(RaftActor.scala:124)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
    at akka.actor.ActorCell.invoke$$original(ActorCell.scala:548)
    at akka.actor.ActorCell.invoke(ActorCell.scala:61)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run$$original(Mailbox.scala:231)
    at akka.dispatch.Mailbox.run(Mailbox.scala:32)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

```
ERROR   akka.actor.OneForOneStrategy    xxx-akka.actor.internal-dispatcher-14 akka://xxx/system/sharding/raft-shard-xxx-replica-group-3/2/2      -       requirement failed: Cannot select the entries (1-7610) unless RaftActor have applied the entries to the entities (lastApplied: 0)       java.lang.IllegalArgumentException: requirement failed: Cannot select the entries (1-7610) unless RaftActor have applied the entries to the entities (lastApplied: 0)
    at scala.Predef$.require(Predef.scala:337)
    at lerna.akka.entityreplication.raft.RaftMemberData.selectEntityEntries(RaftMemberData.scala:375)
    at lerna.akka.entityreplication.raft.RaftMemberData.selectEntityEntries$(RaftMemberData.scala:368)
    at lerna.akka.entityreplication.raft.RaftMemberDataImpl.selectEntityEntries(RaftMemberData.scala:539)
    at lerna.akka.entityreplication.raft.RaftActor.receiveFetchEntityEvents(RaftActor.scala:164)
    at lerna.akka.entityreplication.raft.Follower$$anonfun$followerBehavior$1.applyOrElse(Follower.scala:32)
    at akka.actor.Actor.aroundReceive(Actor.scala:537)
    at akka.actor.Actor.aroundReceive$(Actor.scala:535)
    at lerna.akka.entityreplication.raft.RaftActor.akka$persistence$Eventsourced$$super$aroundReceive(RaftActor.scala:124)
    at akka.persistence.Eventsourced$$anon$4.stateReceive(Eventsourced.scala:923)
    at akka.persistence.Eventsourced.aroundReceive$$original(Eventsourced.scala:251)
    at akka.persistence.Eventsourced.aroundReceive(Eventsourced.scala:148)
    at akka.persistence.Eventsourced.aroundReceive$(Eventsourced.scala:250)
    at lerna.akka.entityreplication.raft.RaftActor.aroundReceive(RaftActor.scala:124)
    at akka.actor.ActorCell.receiveMessage(ActorCell.scala:580)
    at akka.actor.ActorCell.invoke$$original(ActorCell.scala:548)
    at akka.actor.ActorCell.invoke(ActorCell.scala:61)
    at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:270)
    at akka.dispatch.Mailbox.run$$original(Mailbox.scala:231)
    at akka.dispatch.Mailbox.run(Mailbox.scala:32)
    at akka.dispatch.Mailbox.exec(Mailbox.scala:243)
    at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
    at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
    at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
    at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
    at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)
```

**Comment by xirc** [comment]
Related codes are the following:

https://github.com/lerna-stack/akka-entity-replication/blob/abe3af97c2e00ef2d75a23d83c6f045d74fdc904/src/main/scala/lerna/akka/entityreplication/raft/RaftMemberData.scala#L368-L378

https://github.com/lerna-stack/akka-entity-replication/blob/abe3af97c2e00ef2d75a23d83c6f045d74fdc904/src/main/scala/lerna/akka/entityreplication/raft/RaftMemberData.scala#L405-L418

**Comment by xirc** [comment]
We've added some debug logs and diagnosed one RaftActor state change.

```
xxx:36:20.707 === [Follower] Applying event [FollowedLeaderCommit]. state diff: [commitIndex: 6955 -> 6966, lastApplied: 6955 -> 6966] ===
xxx:36:20.781 === [Follower] Applying event [AppendedEntries]. state diff: [replicatedLog: ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1099 entries with indices Some(5825)...Some(6923)) -> ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1115 entries with indices Some(5825)...Some(6939))] ===
xxx:36:20.781 === [Follower] Applying event [FollowedLeaderCommit]. state diff: - ===
xxx:36:20.781 === [Follower] Applying event [BecameFollower]. state diff: - ===
xxx:36:20.795 === [Follower] Applying event [AppendedEntries]. state diff: [replicatedLog: ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1115 entries with indices Some(5825)...Some(6939)) -> ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1131 entries with indices Some(5825)...Some(6955))] ===
xxx:36:20.795 === [Follower] Applying event [FollowedLeaderCommit]. state diff: - ===
xxx:36:20.795 === [Follower] Applying event [BecameFollower]. state diff: - ===
xxx:36:20.802 === [Follower] Applying event [AppendedEntries]. state diff: [replicatedLog: ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1131 entries with indices Some(5825)...Some(6955)) -> ReplicatedLog(ancestorTerm=Term(2), ancestorIndex=5824, 1019 entries with indices Some(5825)...Some(6843))] ===
```

As the above logs, RaftActor deleted its log entries (including committed entries).

**Comment by xirc** [comment]
RaftActor saves entire `AppendEntries.entries` as `AppendedEntries` event (not touched, which might truncate existing  (committed) entries).

Instead, RaftActor should 
* truncate existing entries only if the received entries contain conflict with existing ones
* truncate no entries if the received entries only contain existing ones

or `AppendedEntries` event replay should handle such things.

https://github.com/lerna-stack/akka-entity-replication/blob/f77939c4463107b52e4fe62e46918e2e07fe1df9/src/main/scala/lerna/akka/entityreplication/raft/Follower.scala#L95-L121

https://github.com/lerna-stack/akka-entity-replication/blob/f77939c4463107b52e4fe62e46918e2e07fe1df9/src/main/scala/lerna/akka/entityreplication/raft/RaftMemberData.scala#L388-L393

https://github.com/lerna-stack/akka-entity-replication/blob/f77939c4463107b52e4fe62e46918e2e07fe1df9/src/main/scala/lerna/akka/entityreplication/raft/RaftActor.scala#L210-L213

https://github.com/lerna-stack/akka-entity-replication/blob/f77939c4463107b52e4fe62e46918e2e07fe1df9/src/main/scala/lerna/akka/entityreplication/raft/RaftMemberData.scala#L107-L111

https://github.com/lerna-stack/akka-entity-replication/blob/f77939c4463107b52e4fe62e46918e2e07fe1df9/src/main/scala/lerna/akka/entityreplication/raft/model/ReplicatedLog.scala#L82-L85
