### ISSUE TITLE
Release Job of v2.3.0 failed

### ISSUE THREAD

**Issue by xirc** [lerna-stack/akka-entity-replication#214]
The job logs the following messages:

https://github.com/lerna-stack/akka-entity-replication/actions/runs/5308022311/jobs/9607508359

```
[info] gpg: no default secret key: unusable secret key
[info] gpg: signing failed: unusable secret key
Error:  java.lang.RuntimeException: Failure running 'gpg --batch --passphrase *** --detach-sign --armor --use-agent --output /home/runner/work/akka-entity-replication/akka-entity-replication/core/target/scala-2.13/akka-entity-replication_2.13-2.3.0.pom.asc /home/runner/work/akka-entity-replication/akka-entity-replication/core/target/scala-2.13/akka-entity-replication_2.13-2.3.0.pom'.  Exit code: 2
Error:  	at scala.sys.package$.error(package.scala:30)
Error:  	at com.jsuereth.sbtpgp.CommandLineGpgSigner.sign(PgpSigner.scala:74)
Error:  	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$2(PgpSettings.scala:151)
Error:  	at scala.collection.TraversableLike.$anonfun$flatMap$1(TraversableLike.scala:245)
Error:  	at scala.collection.immutable.Map$Map4.foreach(Map.scala:236)
Error:  	at scala.collection.TraversableLike.flatMap(TraversableLike.scala:245)
Error:  	at scala.collection.TraversableLike.flatMap$(TraversableLike.scala:242)
Error:  	at scala.collection.AbstractTraversable.flatMap(Traversable.scala:108)
Error:  	at com.jsuereth.sbtpgp.PgpSettings$.$anonfun$signingSettings$1(PgpSettings.scala:146)
Error:  	at scala.Function1.$anonfun$compose$1(Function1.scala:49)
Error:  	at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:62)
Error:  	at sbt.std.Transform$$anon$4.work(Transform.scala:67)
Error:  	at sbt.Execute.$anonfun$submit$2(Execute.scala:281)
Error:  	at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:19)
Error:  	at sbt.Execute.work(Execute.scala:290)
Error:  	at sbt.Execute.$anonfun$submit$1(Execute.scala:281)
Error:  	at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
Error:  	at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
Error:  	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
Error:  	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
Error:  	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
Error:  	at java.lang.Thread.run(Thread.java:748)
```

**Comment by xirc** [comment]
Because the key was expired, I've renewed the key.
I've confirmed that the release job succeeded:
https://github.com/lerna-stack/akka-entity-replication/actions/runs/5308022311
